version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Порт для тесту береться зі змінних, за замовчуванням 8080
    ports:
      - '8080:3000'
    container_name: app
    restart: unless-stopped
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-MyPassword05}
      # DATABASE_URL формуємо для прізми з інших змінних, щоб не дублювати інформацію
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-MyPassword05}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-e_commerce_filmsdb}?schema=public
      - TMDB_API_KEY=${TMDB_API_KEY:-dummy_key}
      - JWT_SECRET=${JWT_SECRET:-dummy_secret_key_123}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-3600}
    depends_on:
      db:
        # App почне запуск ТІЛЬКИ коли healthcheck бази даних скаже "ready"
        condition: service_healthy
    command: sh -c "npx prisma migrate deploy && node prisma/seed.js && exec node dist/src/main.js"

  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-MyPassword05}
      POSTGRES_DB: ${DB_NAME:-db}
    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME:-db}']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
