apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Звертаємося до сервісу бази даних усередині K8s
  DB_HOST: 'postgres-svc'
  DB_PORT: '5432'
  DB_NAME: 'e_commerce_filmsdb'
  DB_USER: 'postgres'
