apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData: # stringData дозволяє писати текст без base64 кодування
  DB_PASSWORD: 'MyPassword05'
  DATABASE_URL: 'postgresql://postgres:MyPassword05@postgres-svc:5432/e_commerce_filmsdb?schema=public'
  TMDB_API_KEY: 'dummy_key'
  JWT_SECRET: 'dummy_secret_key_123'
  JWT_EXPIRES_IN: '3600'
