apiVersion: v1
kind: Service
metadata:
  name: ecommerce-app-svc
spec:
  type: ClusterIP # Вимога: тип ClusterIP
  selector:
    app: ecommerce-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
