name: Lab 4 Grading

on:
  push:
  workflow_dispatch:

jobs:
  validate-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Helm вже встановлений на ubuntu-latest, тому просто перевіряємо версію
      - name: Verify Helm installation
        run: helm version
      # Для dry-run потрібен API-сервер Kubernetes
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.10.0

      - name: Run Grading Script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh
